name: drupsby
recipe: drupal8

config:
  webroot: web
  via: nginx
  php: '7.2'
  database: mariadb:10.1

tooling:
  build.sh:
    service: appserver
    description: Execute build.sh
    cmd:
      - ./build.sh
  codeception:
    service: appserver
    description: Run codeception
    cmd:
    - ./vendor/bin/codecept

services:
  database:
    portforward: 13334

  appserver:
    build_as_root:
      - "apt-get update -y"
      - "apt-get install sudo nano python-yaml -y"
    overrides:
      environment:
        WKV_SITE_ENV: lando
        DB_PASS_DRUPAL: drupal8
        DB_USER_DRUPAL: drupal8
        DB_HOST_DRUPAL: database
        DB_NAME_DRUPAL: drupal8
        SITE_URL: 'https://nginx'
        DRUSH_OPTIONS_URI: https://drupsby.lndo.site
